builders:
  # parse_layout:
  #   import: 'package:markdown_blog_gen/builder.dart'
  #   builder_factories: ['parseLayout']
  #   build_extensions: {'.dart': ['']}
  #   auto_apply: root_package
  #   build_to: source
  #   runs_before: [":markdown_blog_gen"]

  markdown_blog_gen:
    import: 'package:markdown_blog_gen/builder.dart'
    builder_factories: ['markdownBlogGen']
    build_extensions: {'.md': ['.html']}
    auto_apply: root_package
    build_to: source
    runs_before: [':index_builder']

  index_builder:
    import: 'package:markdown_blog_gen/builder.dart'
    builder_factories: ['indexBuilder']
    build_extensions: {'.dart.html': ['.html']}
    auto_apply: root_package
    build_to: source

# targets:
#   $default:
#     builders:
#       :markdown_blog_gen:
#         enabled: true