builders:
  markdown_blog_gen:
    import: 'package:markdown_blog_gen/builder.dart'
    builder_factories: ['markdownBlogGen']
    build_extensions: {'^lib/blog/{{}}.md': ['web/blog/{{}}.html']}
    auto_apply: root_package
    build_to: source
    runs_before: [':index_builder']
    defaults:
      generate_for:
        include:
        - lib/**

  index_builder:
    import: 'package:markdown_blog_gen/builder.dart'
    builder_factories: ['indexBuilder']
    build_extensions: {'^lib/{{}}.html': ['web/{{}}.html']}
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        include:
        - lib/**

# targets:
#   $default:
#     builders:
#       :markdown_blog_gen:
#         enabled: true